Testproject/Testproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('collegeapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Testproject/collegeapp/urls.py
from django.urls import path
from . import views
app_name='collegeapp'

urlpatterns = [
    path("",views.index,name="index"),
    path("login/",views.login,name='login'),
    path("register/",views.register,name='register'),
    path("new/",views.new,name='new'),
    path("submit/",views.submit,name='submit')

]

Testproject/collegeapp/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    name=models.CharField(max_length=250)

    def __str__(self):
        return self.name
class Courses(models.Model):
    cname = models.CharField(max_length=250)
    course=models.ForeignKey(Department,on_delete=models.CASCADE)


    def __str__(self):
        return self.cname

Testproject/collegeapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from collegeapp.models import Department, Courses


# Create your views here.
def index(request):
    return render(request,"index.html")
def login(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=User(username=username,password=password)
        user.save()


    return render(request,"login.html")

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        password1 = request.POST.get('password1')
        user=User(username=username,password=password)
        user.save()
        return redirect("/login")
    return render(request,"register.html")
def new(request):
    department=Department.objects.all()
    courses=Courses.objects.all()
    return render(request,"new.html",{'department':department,'courses':courses})
def submit(request):
    return render(request,'submit.html')

Testproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link rel="stylesheet" href= href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

Testproject/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900' %}" rel="stylesheet">

    <title> School HTML5 Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-grad-school.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">
<!--

TemplateMo 557 Grad School

https://templatemo.com/tm-557-grad-school

-->
  </head>

<body>


  <!--header-->
  <header class="main-header clearfix" role="header">
    <div class="logo">
      <a href="#"><em>College</em> Store</a>
    </div>
    <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
    <nav id="menu" class="main-nav" role="navigation">
      <ul class="main-menu">
        <li><a href="#section1">Home</a></li>
        <li class="has-submenu"><a href="#section2">Department</a>
          <ul class="sub-menu">
            <li><a href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Commerce">Commerce</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Humanities">Humanities</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Social_work">Social work</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Graphics">Graphics</a></li>
<!--            <li><a href="{% static 'https://templatemo.com/about' %}" rel="sponsored" class="external">External URL</a></li>-->
          </ul>
        </li>
        <li><a href="{% url 'collegeapp:login' %}">Login</a></li>

        <!-- <li><a href="#section5">Video</a></li> -->
        <li><a href="{% url 'collegeapp:register' %}">Register</a></li>
<!--        <li><a href="https://templatemo.com" class="external">External</a></li>-->
      </ul>
    </nav>
  </header>

  <!-- ***** Main Banner Area Start ***** -->
  <section class="section main-banner" id="top" data-section="section1">
      <video autoplay muted loop id="bg-video">
          <source src="{% static 'assets/images/course-video.mp4' %}" type="video/mp4" />
      </video>

      <div class="video-overlay header-text">
          <div class="caption">
              <h6>Graduate College</h6>

          </div>
      </div>
  </section>
  <!-- ***** Main Banner Area End ***** -->
<section class="section coming-soon" data-section="section3">
    <div class="container">
      <div class="row">

             <div class="col-lg-6">

            <h1><b style="color:white;font-size:70px;">Your Classroom</b></h1>
              <div class="main-button">
                  <div class="scroll-to-section"><a href="{% url 'collegeapp:new' %}">Discover more</a></div>
              </div>

        </div>
            </div>
          </div>



  </section>

Testproject/templates/login.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<form  action="" method="post">
    {% csrf_token %}
    <input type="text"   name="username"  placeholder="Enter your username"><br>
    <input type="password"   name="password"  placeholder="Enter your password"><br>
    <button type="submit">Submit</button><br>
    <a href="/register">Register link</a>


</form>
</body>
{% endblock %}

Testproject/templates/new.html
{% extends 'base.html' %}
{% block body %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>

<script>

$(document).ready(function(){

 var department = $("#dd1");
 var courses = $("#dd2");
 var $options = courses.find('option');
 department.on('change',function(){
    courses.html($options.filter('[value="'+ this.value  +'"]'));
 }).trigger('change');
});
</script>


<form>
  <div>
    <label><b>Name</b></label><br>
    <input type="text"  name="username" placeholder="Enter your Name">
  </div>
  <div>
    <label><b>DOB</b></label><br>
    <input type="date" name="date" placeholder="Enter your DOB">
  </div>
  <div>
    <label><b>Age</b></label><br>
    <input type="text"  name="age" placeholder="Enter your Age">
  </div>
  <div>
    <label><b>Gender</b></label><br>
    <input type="radio"  name="rdbGender">Male
    <input type="radio"  name="rdbGender">Female<br>
  </div>
   <div>
    <label><b>Phone number</b></label><br>
    <input type="text"  name="number" placeholder="Enter your Phone number">
  </div>
  <div>
    <label><b>Email</b></label><br>
    <input type="email" name="email" placeholder="Enter email">
  </div>
  <div>
    <label><b>Address</b></label><br>
    <input type="text"  name="address" placeholder="Enter your Address">
  </div>
    <div><h5>Department</h5>
    <select name="Department" id="dd1" >
        <option value="">--Choose Department--</option>
        {% for department in department %}
        <option value="{{department}}">{{department.name}}</option>
        {% endfor %}

    </select>
        <div><h5>Courses</h5>
    <select name="courses"  id="dd2">
        <option value="">--Choose Courses--</option>
        {% for courses in courses %}
        <option value="{{courses}}">{{courses.name}}</option>
        {% endfor %}

    </select>

    <div><h5>Purpose</h5>
    <select name="Purpose">
        <option value="">--Choose Purpose--</option>
        <option value="Enquiry">Enquiry</option>
        <option value="Place">Place</option>
        <option value="Order">Order</option>
        <option value="Return">Return</option>
    </select>
</div>


</div>
    <label><b>Materials Provide</b></label><br>
    <input type="checkbox"  name="rdbQuestion">Notebook
    <input type="checkbox" name="rdbQuestion">Pen
    <input type="checkbox"  name="rdbQuestion">Exam papers
    <input type="checkbox"  name="rdbQuestion">Tools<br>
  </div>

  <a  class="btn btn-primary" href="{% url 'collegeapp:submit' %}">Submit</a>

        <button type= "submit" class="btn btn-success">Log out</button>

</form>
{% endblock %}

Testproject/templates/register.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<form  action="" method="post">
    {% csrf_token %}
    <input type="text"   name="username"  placeholder="Enter your username"><br>
    <input type="password" name="password"  placeholder="Enter your password"><br>
    <input type="password" name="password1"  placeholder="Confirm your password"><br>
    <input type="submit">


</form>
</body>
{% endblock %}

Testproject/templates/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
<form method="post">
    {% csrf_token %}
  <p>Please recheck your information and confirm </p>
    <button type="confirm">Confirm</button>
    <a href="/" >Back to Home</a>


</form>
</body>
</html>